namespace: reactive-mesh-authz
resources:
  - ../reactive
  - ../../idp-keycloak
patches:
  - path: envoy-reactive-configmap.yaml
    target:
      version: v1
      kind: ConfigMap
      name: envoy-reactive-config
