namespace: reactive-mesh-authz
resources:
  - ../../base
  - ../../idp-demo
  - openfga.yaml
  - envoy-baseline-configmap.yaml
  - envoy-baseline.yaml
patches:
  - target:
      kind: Deployment
      name: baseline-authz
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: openfga
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_ADDR
          value: openfga:8080
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_POLICY_USER
          value: user:policy
  - target:
      kind: Deployment
      name: receiver
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_SYNC_ENABLED
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_ADDR
          value: openfga:8080
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_STORE_NAME
          value: reactive-mesh-authz-openfga
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENFGA_POLICY_USER
          value: user:policy
