apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-reactive-mesh
  namespace: reactive-mesh-authz
data:
  reactive-mesh-realm.json: |
    {
      "realm": "reactive-mesh",
      "enabled": true,
      "registrationAllowed": false,
      "resetPasswordAllowed": false,
      "rememberMe": false,
      "clients": [
        {
          "clientId": "reactive-mesh-cli",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "serviceAccountsEnabled": false,
          "protocol": "openid-connect",
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ],
      "users": [
        {
          "username": "alice",
          "enabled": true,
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "alice-pass",
              "temporary": false
            }
          ]
        }
      ]
    }
